/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package animatedlabel;

/**
 *
 * @author Albert
 */
public class AnimatedLabelPanel extends javax.swing.JPanel {

    private String text;
    private String appText;
    private int delay;
    private boolean animate = false;
    
    public AnimatedLabelPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtText = new javax.swing.JTextField();
        btnSetText = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAppendText = new javax.swing.JTextField();
        btnSetAppendText = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sldDelay = new javax.swing.JSlider();
        btnAnimate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDemo = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        jLabel1.setText("Text");

        btnSetText.setText("Set");
        btnSetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTextActionPerformed(evt);
            }
        });

        jLabel2.setText("AppendText");

        btnSetAppendText.setText("Set");
        btnSetAppendText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAppendTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Delay");

        sldDelay.setMajorTickSpacing(100);
        sldDelay.setMaximum(1000);
        sldDelay.setPaintLabels(true);
        sldDelay.setPaintTicks(true);
        sldDelay.setSnapToTicks(true);
        sldDelay.setValue(100);
        sldDelay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDelayStateChanged(evt);
            }
        });

        btnAnimate.setText("Animate");
        btnAnimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimateActionPerformed(evt);
            }
        });

        jLabel4.setText("Animated Label");

        txtDemo.setText("Demo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(sldDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppendText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSetText)
                            .addComponent(btnSetAppendText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnimate)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAppendText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetAppendText))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sldDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimate))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTextActionPerformed
        text = txtText.getText();
    }//GEN-LAST:event_btnSetTextActionPerformed

    private void btnSetAppendTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetAppendTextActionPerformed
        appText = txtAppendText.getText();
    }//GEN-LAST:event_btnSetAppendTextActionPerformed

    private void sldDelayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDelayStateChanged
        delay = sldDelay.getValue();
    }//GEN-LAST:event_sldDelayStateChanged

    private void btnAnimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimateActionPerformed
        animate = true;
        
    }//GEN-LAST:event_btnAnimateActionPerformed

    public AnimatedLabel getSelectedValue(){
        return new AnimatedLabel(text, appText, delay, animate);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimate;
    private javax.swing.JButton btnSetAppendText;
    private javax.swing.JButton btnSetText;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider sldDelay;
    private javax.swing.JTextField txtAppendText;
    private javax.swing.JTextField txtDemo;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables
}
